#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=200G
#SBATCH -p compute-64-512
#SBATCH --array=0-5
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=30
#SBATCH --job-name=busco #Change Job Name
#SBATCH -o busco_%A_%a.out.out
#SBATCH -e busco_%A_%a.out.err

module load busco/4.1.0

idlist=(SIM NAR ARC MET REY TUK)

id=${idlist[$SLURM_ARRAY_TASK_ID]}

busco -m tran -i filt_trans/${id}/${id}*.fasta -l actinopterygii_odb10 -o ${id}_busco -q -c 30 -f
