#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=80G
#SBATCH -p compute-64-512
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=seqkit #Change Job Name
#SBATCH -o seqkit.out
#SBATCH -e seqkit.err

PATH=~/miniconda3/bin/:$PATH

seqkit grep -f SvsA_Sig_Genes_genename.tsv -r -n longest_pep_ln/SIM_longest_orfs.pep -o SIM_sig_pep.fa





