#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=80G
#SBATCH -p compute-64-512
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=signal #Change Job Name
#SBATCH -o signal.out
#SBATCH -e signal.err

PATH=~/miniconda3/bin/:$PATH

source activate prot_location

signalp6 --fastafile toxinpred2_out/SIM/SIM_sig_pep.fa -org eukarya -od signal_output/
