#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=80G
#SBATCH --array=0-99
#SBATCH -p compute-24-96
#SBATCH --ntasks=1
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=10
#SBATCH --job-name=cluster_array #Change Job Name
#SBATCH -o cluster_%A_%a.out
#SBATCH -e cluster_%A_%a.err

module load clustal-omega/1.2.4

filelist=(ls seq_ln/)
file=${filelist[$SLURM_ARRAY_TASK_id]}

#program
base=$(basename "$file" .fasta)
clustalo -i seq_ln/${file} --threads=10 > cluster_alignments/${base}.fas
