#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=80G
#SBATCH --array=0-99
#SBATCH -p compute-24-96
#SBATCH --ntasks=1
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=10
#SBATCH --job-name=hmm_array #Change Job Name
#SBATCH -o hmm_%A_%a.out
#SBATCH -e hmm_%A_%a.err

SP=
echo "Running for ${SP}"
GENOME=${SP}_transdecoder/longest_orfs.pep
filelist=(seq_ln/*.fasta)

# Get the current file for this array task
file=${filelist[$SLURM_ARRAY_TASK_ID]}

# Extract base name (remove path and extension)
base=$(basename "$file" .fasta)
./hmm_model.sh -i ${base}.fas -d cluster_alignments -g '$GENOME' -n ${SP}
