#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=200G
#SBATCH -p compute-64-512
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --job-name=longest #Change Job Name
#SBATCH -o longest.out
#SBATCH -e longest.err

module load trinity
PATH=/gpfs/software/ada/trinity/2.11.0/util/misc/:$PATH

for i in ARC MET NAR REY SIM TUK; do 
 cd ~/Venom_Evolution_2024/transcriptomes/longest_iso/${i}/
 get_longest_isoform_seq_per_trinity_gene.pl Trinity.fasta > ${i}_longest_isoform.fasta
done
