#!/bin/bash
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=chh20csu@uea.ac.uk
#SBATCH -t 7-00:00:00
#SBATCH --mem=200G
#SBATCH -p compute-64-512
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --job-name=ortho #Change Job Name
#SBATCH -o ortho.out
#SBATCH -e ortho.err

module load ncbi-blast/2.10.1+
module load OrthoFinder/2.5.2

cd /gpfs/home/chh20csu/Venom_Evolution_2024/transcriptomes/longest_iso/

orthofinder.py -t 40 -d -f renamed_fasta 
